site_name: Tinker Board Series Documentation
site_url: https://tinkerboard.github.io/

nav:
  - Home: 'index.md'
  - 'Getting Started': 'getting-started.md'
  - Releases: 'releases.md'
  - ASUS:
    - ASUS: 'https://www.asus.com" target="_blank'
    - 'ASUS IoT': 'https://iot.asus.com" target="_blank'
  - 'Tinker Board Series':
    - 'Tinker Board Website': 'https://tinker-board.asus.com" target="_blank'
    - 'Tinker Board Forum': 'https://tinker-board.asus.com/forum/" target="_blank'
    - 'Tinker Board Wiki': 'https://github.com/TinkerBoard/TinkerBoard/wiki/" target="_blank'
    - 'GitHub for Tinker Board Series':
      - 'Linux': 'https://github.com/TinkerBoard/" target="_blank'
      - 'Android': 'https://github.com/TinkerBoard-Android/" target="_blank'

theme:
  name: mkdocs
  navigation_depth: 4

markdown_extensions:
  - attr_list